### ISSUE TITLE
If you turn off stereo in 1.3b2 Marathon 1 the game crashes

### ISSUE THREAD

**Issue by kandriod** [Aleph-One-Marathon/alephone#124]
Click the stereo checkbox making it turn off, quit, then reopen the game, it crashes nearly instantly showing this error in windows 
![image](https://user-images.githubusercontent.com/25878306/48458685-38d14580-e77c-11e8-91dd-f69f16f5c5d5.png)

**Comment by orbea** [comment]
In linux turning off `Stereo` works just fine, the sound with mono sounds a bit noisy, but maybe that is normal?

However when I go to turn `Stereo` back on alephone instantly crashes as soon as I hit `Accept`.
```
free(): invalid pointer
Aborted
```
It will also crash sometimes when alephone is starting, closing or just while in the main menu...

When built without optimizations it will crash pretty consistently when starting.
```
corrupted double-linked list
Aborted
```
Here is a backtrace with the SDL2 current master. (https://github.com/spurious/SDL-mirror/commit/e53c04a3e6138343c6737983e7ded23a4a20d632)
```
Reading symbols from alephone...done.
(gdb) r /opt/AlephOne/Marathon
Starting program: /usr/games/alephone /opt/AlephOne/Marathon
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Aleph One Linux 2018-10-06 1.3b2
https://alephone.lhowon.org/

Original code by Bungie Software <http://www.bungie.com/>
Additional work by Loren Petrich, Chris Pruett, Rhys Hill et al.
TCP/IP networking by Woody Zenfell
Expat XML library by James Clark
SDL port by Christian Bauer <Christian.Bauer@uni-mainz.de>

This is free software with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
For details, see the file COPYING.

Built with network play enabled.

Built with Lua scripting enabled.
[New Thread 0x7fffe85d7700 (LWP 5851)]
[New Thread 0x7fffe7d56700 (LWP 5852)]
[New Thread 0x7fffe7311700 (LWP 5855)]

Thread 1 "alephone" received signal SIGSEGV, Segmentation fault.
0x00007ffff4a7caf3 in _int_malloc () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff4a7caf3 in _int_malloc () from /lib64/libc.so.6
#1  0x00007ffff4a83441 in calloc () from /lib64/libc.so.6
#2  0x00007ffff5709ff1 in SDL_calloc_REAL (nmemb=6, size=16)
    at /tmp/SBo/SDL2/src/stdlib/SDL_malloc.c:5344
#3  0x00007ffff56bf12f in SDL_JoystickOpen_REAL (device_index=0)
    at /tmp/SBo/SDL2/src/joystick/SDL_joystick.c:343
#4  0x00007ffff56bdcb2 in SDL_GameControllerOpen_REAL (device_index=0)
    at /tmp/SBo/SDL2/src/joystick/SDL_gamecontroller.c:1557
#5  0x00007ffff56aa41c in SDL_GameControllerOpen (a=0)
    at /tmp/SBo/SDL2/src/dynapi/SDL_dynapi_procs.h:171
#6  0x00000000004c466d in joystick_added (device_index=0) at joystick_sdl.cpp:70
#7  0x00000000004c44f1 in initialize_joystick () at joystick_sdl.cpp:50
#8  0x00000000004195e3 in initialize_application () at shell.cpp:591
#9  0x00000000004184ea in main (argc=0, argv=0x7fffffffe278) at shell.cpp:335
(gdb) bt full
#0  0x00007ffff4a7caf3 in _int_malloc () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff4a83441 in calloc () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff5709ff1 in SDL_calloc_REAL (nmemb=6, size=16)
    at /tmp/SBo/SDL2/src/stdlib/SDL_malloc.c:5344
        mem = 0x20
#3  0x00007ffff56bf12f in SDL_JoystickOpen_REAL (device_index=0)
    at /tmp/SBo/SDL2/src/joystick/SDL_joystick.c:343
        driver = 0x7ffff58d73e0 <SDL_LINUX_JoystickDriver>
        instance_id = 0
        joystick = 0xe31fe0
        joysticklist = 0x0
        joystickname = 0xc586a0 "Sony PLAYSTATION(R)3 Controller"
#4  0x00007ffff56bdcb2 in SDL_GameControllerOpen_REAL (device_index=0)
    at /tmp/SBo/SDL2/src/joystick/SDL_gamecontroller.c:1557
        instance_id = 0
        gamecontroller = 0xd453c0
        gamecontrollerlist = 0x0
        pSupportedController = 0xcc0dc0
#5  0x00007ffff56aa41c in SDL_GameControllerOpen (a=0)
    at /tmp/SBo/SDL2/src/dynapi/SDL_dynapi_procs.h:171
No locals.
#6  0x00000000004c466d in joystick_added (device_index=0) at joystick_sdl.cpp:70
        controller = 0x0
        instance_id = 32767
#7  0x00000000004c44f1 in initialize_joystick () at joystick_sdl.cpp:50
        i = 0
        fs = {name = "", err = 2}
#8  0x00000000004195e3 in initialize_application () at shell.cpp:591
        retval = 0
        dsp_insert_pos = 0
        dsp_delete_pos = 0
        data_env = 0x0
#9  0x00000000004184ea in main (argc=0, argv=0x7fffffffe278) at shell.cpp:335
        app_name_version = "Aleph One Linux 2018-10-06 1.3b2\000v\275\000\000\000\
000\000\000\006\265\000\000\000\000\000\200\340\377\377\377\177\000\000\004HB\000\000\000\000\000\030'\275\364\377\177\000\000\000\006\265\000\000\000\000\000\240\340\377\377\377\177\000\000`\034B\000\000\000\000\000h\342\377\377\377\177\000\000\000\006\265\000\000\000\000\000\300\340\377\377\377\177\000\000(t\275\364\377\177\000\000\226\355A\000\000\000\000\000\331Ȣ\364\377\177\000\000\340\340\377\377\377\177\000\000\340ߩ\000\000\000\000\000\000\341\377\377\377\177\000\000\330ߩ\000\000\000\000\000\002\000\000\000\000\000\000\000\273\332A\000\000\000\000\000\330ߩ\000\000\000\000\000\377\377\000\000"...
        prg_name = 0x7fffffffe566 "/usr/games/alephone"
(gdb) t a a f

Thread 4 (Thread 0x7fffe7311700 (LWP 5855)):
#0  0x00007ffff4afc329 in poll () from /lib64/libc.so.6

Thread 3 (Thread 0x7fffe7d56700 (LWP 5852)):
#0  0x00007ffff5190190 in nanosleep () from /lib64/libpthread.so.0

Thread 2 (Thread 0x7fffe85d7700 (LWP 5851)):
#0  0x00007ffff518c2a3 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0

Thread 1 (Thread 0x7fffee5a1580 (LWP 5847)):
#0  0x00007ffff4a7caf3 in _int_malloc () from /lib64/libc.so.6
```
This setting can be changed back by editing the `Marathon Preferences` file.
```
-  <sound channels="32" volume="2" music_volume="4" flags="56" rate="44100" samples="1024" volume_while_speaking="32" mute_while_transmitting="true"/>
+  <sound channels="32" volume="2" music_volume="4" flags="59" rate="44100" samples="1024" volume_while_speaking="32" mute_while_transmitting="true"/>
```

**Comment by ccallahan** [comment]
I hate to be the bearer of bad news, but the patch that was committed for this bug made it impossible to compile on Windows when our CI server sucked it up the other day. Reverting this change in the code fixed the compilation errors.

Internal JIRA Ticket: https://jira.chancecallahan.com/browse/A1-3
The build that failed when compiling is https://bamboo.chancecallahan.com/browse/A1-XCMP-9 and the build that we reverted the changes in is https://bamboo.chancecallahan.com/browse/A1-INTEST-WIN64-2 (still in progress at post time, but we have more than passed the part where it choked).

CC: @tbcr

**Comment by ccallahan** [comment]
Never mind! It's still broke!

https://bamboo.chancecallahan.com/browse/A1-INTEST-WIN64-2
